"""Explicit write mode for agent instruction init."""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

from agent_rules_kit.init_plan import InitPlanAction, build_init_plan

BASELINE_AGENTS_CONTENT = """# Agent Instructions

These baseline instructions were generated by agent-rules-kit.
Review and adapt them before relying on them for a specific project.

## Scope

These instructions apply from the repository root unless a more specific instruction file
defines a narrower scope.

## Authority

Follow explicit user requests first. Then follow this file and any more specific
instruction files for the files being changed.

## Secret handling

Do not commit, print, or log secrets, tokens, credentials, API keys, private URLs, or private data.

## Command execution

Read the repository before changing files.
Ask for explicit confirmation before destructive commands or broad filesystem changes.

## Review and CI

Keep the repository review process, CI requirements, branch protection, and maintainer
approval intact.
"""


@dataclass(frozen=True, slots=True)
class WrittenInitFile:
    """A file action performed by init write mode."""

    path: str
    action: InitPlanAction
    backup_path: str | None


@dataclass(frozen=True, slots=True)
class InitWriteResult:
    """Result of explicit init write mode."""

    repository: str
    files: tuple[WrittenInitFile, ...]


def write_init_files(root: Path | str) -> InitWriteResult:
    """Write baseline init files, backing up existing files before replacement."""
    plan = build_init_plan(root)
    root_path = Path(root)
    written_files: list[WrittenInitFile] = []

    for planned_file in plan.files:
        target = root_path / planned_file.path
        backup_path: Path | None = None

        if planned_file.action == InitPlanAction.BACKUP_AND_REPLACE:
            backup_path = _next_backup_path(target)
            shutil.copy2(target, backup_path)

        _write_text_atomic(target, BASELINE_AGENTS_CONTENT)

        written_files.append(
            WrittenInitFile(
                path=planned_file.path,
                action=planned_file.action,
                backup_path=(
                    backup_path.relative_to(root_path).as_posix()
                    if backup_path is not None
                    else None
                ),
            )
        )

    return InitWriteResult(
        repository=plan.repository,
        files=tuple(written_files),
    )


def _write_text_atomic(target: Path, content: str) -> None:
    temporary_path = _next_available_path(
        target.with_name(f".{target.name}.agent-rules-kit.tmp")
    )

    try:
        temporary_path.write_text(content, encoding="utf-8")
        temporary_path.replace(target)
    finally:
        if temporary_path.exists():
            temporary_path.unlink()


def _next_backup_path(target: Path) -> Path:
    return _next_available_path(target.with_name(f"{target.name}.agent-rules-kit.bak"))


def _next_available_path(candidate: Path) -> Path:
    if not candidate.exists():
        return candidate

    for index in range(1, 1000):
        indexed_candidate = candidate.with_name(f"{candidate.name}.{index}")
        if not indexed_candidate.exists():
            return indexed_candidate

    raise RuntimeError(f"could not find available backup path for: {candidate}")


__all__ = [
    "BASELINE_AGENTS_CONTENT",
    "InitWriteResult",
    "WrittenInitFile",
    "write_init_files",
]
